#baseURL = "https://jowen.vercel.app/"
baseURL = "https://jowen.pages.dev/"
title = "Jowen's Blog"
theme = "hugo-coder"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"

enableRobotsTXT = true
canonifyURLs = true

enableGitInfo = true
enableEmoji = true

paginate = 9999

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pluralizelisttitles = false

FootnoteReturnLinkContents = "â†‘"

[markup.goldmark.renderer]
    unsafe= true

[outputs]
  page     = ["HTML", "AMP"]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
    author = "Jowen"
    info1 = "ğŸ“š Lifelong Learner"
    info2 = "ğŸ‘¨â€ğŸ’» Developer"
#    info3 = "ğŸ’´ ETF Trader"
    description = "To be the best."
    keywords = "life,dev,developer,IT technology"
    avatarurl = "images/avatar.jpg"
    logoImg = "images/avatar.jpg"
    header = "BMPI.dev"

    twitter = "jowen"
    github = "jowen"
    telegram = "jowen"
    zhihu = "jowen"

    favicon_32 = "images/f3/favicon-32x32.png"
    favicon_16 = "images/f3/favicon-16x16.png"

    # footercontent = "self/dev/money"

    hidecredits = true
    hidecopyright = false

    series = true

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    math = true
    custom_css = ["/css/main.css"]
    custom_js = ["/js/lazysizes.min.js", "/js/flying-pages.min.js", "/js/custom.js"]

    dateFormat = "2006-01-02"

    # AMP
    amp = true
    ampElements = ["amp-ad","amp-analytics"]
    themeColor = "#000000"
    adsensePublisher = "ca-pub-1886683614725279"
    googleAnalytics = "UA-154678195-1"

    # OG
    og_image = "images/bg2.png"

# Comments on github issue
[params.utteranc]
    enable = true
    repo = "Aristohack/jowen"
    issue-term = "pathname"
    theme = "github-light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/Aristohack/"
[[params.social]]
    name = "YouTube"
    icon = "fab fa-youtube"
    weight = 2
    url = "https://www.youtube.com/channel/UCM1XLAEEuRgbqBuzuNwAUfA"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/Jowen_CN"
#[[params.social]]
#    name = "Twitter"
#    icon = "Fab Fa-Instagram"
#    weight = 5
#    url = "https://www.instagram.com/jowen_cn/"
[[params.social]]
    name = "ZhiHu"
    icon = "fab fa-zhihu"
    weight = 6
    url = "https://www.zhihu.com/people/qiao-wen-59-96"
[[params.social]]
    name = "Newsletter"
    icon = "fas fa-envelope"
    weight = 7
    url = "https://tinyletter.com/Jowen"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
                name = "About"
                weight = 1
                url = "/about/"
#            [[languages.en.menu.main]]
#                name = "Self"
#                weight = 2
#                url  = "/self/"
            [[languages.en.menu.main]]
                name = "Bigdata"
                weight = 3
                url  = "/bigdata/"
            [[languages.en.menu.main]]
                name = "Java"
                weight = 4
                url  = "/java/"
#            [[languages.en.menu.main]]
#                name = "Project"
#                weight = 5
#                url  = "/project/"
            [[languages.en.menu.main]]
                name = "Goal"
                weight = 6
                url  = "/goal/"
            [[languages.en.menu.main]]
                name = "Twitter"
                weight = 7
                url  = "https://twitter.com/Jowen_CN"

    [languages.zh-cn]
        languagename = "Chinese"
        title = "Jowençš„åšå®¢"

        [languages.zh-cn.params]
            author = "ä¹”æ–‡æ–‡"
#            info1 = "ğŸ“š ç»ˆèº«å­¦ä¹ è€…"
            info2 = "ğŸ‘¨â€ğŸ’» é«˜çº§ç ”å‘å·¥ç¨‹å¸ˆ"
#            info3 = "ğŸ’´ ETF Trader"
            description = "é€šè¿‡å­¦ä¹ ï¼ˆGTDã€æ—¶é—´ç®¡ç†ã€çŸ¥è¯†ç®¡ç†ã€å†™ä½œã€è´¢åŠ¡ç®¡ç†ï¼‰ã€æŠ€æœ¯åˆ›é€ ï¼ˆå‰ç«¯ã€åç«¯ã€ç§»åŠ¨ç«¯ã€DevOpsï¼‰ã€æŠ•èµ„ï¼ˆæŒ‡æ•°æŠ•èµ„ã€åŸºé‡‘ã€è‚¡ç¥¨ã€å€ºåˆ¸ï¼‰ã€ç½‘èµšé¡¹ç›®ï¼ˆSEOã€Affiliateã€Media Buyã€Nicheã€ç¤¾äº¤åª’ä½“ï¼‰æ¥å»ºç«‹è¢«åŠ¨æ”¶å…¥"
            keywords = "è‡ªæˆ‘æå‡ã€æ—¶é—´ç®¡ç†ã€GTDã€å†™ä½œã€æ‘„å½±ã€ç¬”è®°ç®¡ç†ã€çŸ¥è¯†ç®¡ç†ã€è´¢åŠ¡ç®¡ç†ã€å…¨æ ˆå¼€å‘ã€æŒ‡æ•°æŠ•èµ„ã€åŸºé‡‘ã€è‚¡ç¥¨ã€å€ºåˆ¸ã€SEOã€Affiliateã€Media Buyã€Nicheã€ç¤¾äº¤åª’ä½“ã€è¢«åŠ¨æ”¶å…¥ã€ç½‘èµš"
            # footercontent = "self/dev/money"

        [languages.zh-cn.menu]
            [[languages.zh-cn.menu.main]]
                name = "å…³äº"
                weight = 2
                url = "/about/"
#            [[languages.zh-cn.menu.main]]
#                name = "å­¦ä¹ "
#                weight = 3
#                url  = "/self/"
            [[languages.zh-cn.menu.main]]
                name = "å¤§æ•°æ®"
                weight = 4
                url  = "/bigdata/"
            [[languages.zh-cn.menu.main]]
                name = "Java"
                weight = 5
                url  = "/java/"
#            [[languages.zh-cn.menu.main]]
#                name = "ä¸ªäººé¡¹ç›®"
#                weight = 6
#                url  = "/project/"
            [[languages.zh-cn.menu.main]]
                name = "é•¿æœŸç›®æ ‡"
                weight = 7
                url  = "/goal/"
            [[languages.zh-cn.menu.main]]
                name = "Twitter"
                weight = 8
                url  = "https://twitter.com/Jowen_CN"
